version: "2"

linters:
  default: none
  enable:
    - errcheck
    - errorlint
    - gocritic
    - govet
    - ineffassign
    - staticcheck
    - unused

formatters:
  enable:
    - gofmt
    - goimports
